### PR TITLE
cleanup and few changes

### PR DESCRIPTION
**Pull request by ctf0**
changed the tmlang name from HTML5 to HTML for 3 reasons

- because laravel blade cant pickup the right HL when using HTML5 so the default HTML have to be enabled
- the need to keep changing between HTML5 & HTML ,now u dont
- no more need to disable the default HTML package as now this will override the default and Sublime linter can now work with the new syntax instead of the default.

edited the form input names for easier & faster completion.
removed any snippet < IE8

### CODE REVIEW

**Comment by mrmartineau** [comment]
@ctf0, thanks for your input. I have not seen all of the changes you have made so I cannot be 100% certain on this, but I won't be merging the `tabTrigger` changes you have made because I believe it is easier to type `link` and see all the options for link rather than remembering the different shortcuts. Do you see?

Does removing some of the HTML5 tags break it or is have you done that because Sublime's default HTML package handles these tags?

I will try to comment on some of the other changes inline when I have more time.

**Comment by ctf0** [comment]
for the links it still works as b4 ,u just got a one more character in case u dont want to scroll the whole menu to find what u want ,same goes with the input.

i didn't remove any of the html tags ,i just changed the language file from being HTML5 to HTML because laravel blade works only with HTML and cant recognize the HTML5 + the other reasons i mentioned above.

**Comment by mrmartineau** [comment]
Hi @ctf0, after examining this more thoroughly I will merge your changes. Your reasons for the tabtrigger changes make a lot of sense. Thanks for your help.

**Comment by ctf0** [comment]
np ,glad to help :).

**Pull request merged**
